name: Test Workflow
on:
  workflow_dispatch
  push:
    branches:
      -main
  jobs:
    build:
       runs-on: ubuntu-latest
       steps:
        -name: checkout repository
           uses: actions/checkout@v3
        -name: print message
        run :echo "workflow يعمل بنجاح"
